/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.stockmarketsimulator;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.*;
/**
 *
 * @author parth
 */
public class BuyStocks extends javax.swing.JFrame {
    private int userID;

    public BuyStocks(int userID) {
        this.userID = userID;
        initComponents();
        displayAvailableStocks();
    }

    /**
     * Creates new form BuyStocks
     */
    public BuyStocks() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        StockList = new java.awt.List();
        BuyQuantity = new javax.swing.JTextField();
        BuyButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        AmountReq = new javax.swing.JTextField();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        StockList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StockListMouseClicked(evt);
            }
        });
        StockList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StockListActionPerformed(evt);
            }
        });

        BuyQuantity.setText("1");

        BuyButton.setText("Buy");
        BuyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuyButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Amount Required:");

        AmountReq.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(StockList, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BuyButton)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(BuyQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AmountReq, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(StockList, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BuyQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AmountReq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BuyButton)))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     private void displayAvailableStocks() {
        try {
            Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/smms", "root", "FireRage@007");
            String sql = "SELECT Stock_Name FROM stocks";
            PreparedStatement statement = connection.prepareStatement(sql);
            ResultSet resultSet = statement.executeQuery();

            StockList.removeAll(); // Clear existing items in StockList

            while (resultSet.next()) {
                String stockName = resultSet.getString("Stock_Name");
                StockList.add(stockName);
            }

            resultSet.close();
            statement.close();
            connection.close();
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error retrieving stocks: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    private void StockListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StockListActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StockListActionPerformed

    private void StockListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StockListMouseClicked
        // TODO add your handling code here:
        // TODO add your handling code here:
        String selectedStockName = StockList.getSelectedItem();
        if (selectedStockName != null && !selectedStockName.isEmpty()) {
            try {
                Connection connection = DatabaseConnection.getConnection();
                PreparedStatement getPriceStatement = connection.prepareStatement("SELECT Latest_Price FROM stocks WHERE Stock_Name = ?");
                getPriceStatement.setString(1, selectedStockName);
                ResultSet resultSet = getPriceStatement.executeQuery();

                if (resultSet.next()) {
                    float price = resultSet.getFloat("Latest_Price");
                    int quantity = Integer.parseInt(BuyQuantity.getText());

                    float totalAmountRequired = price * quantity;
                    AmountReq.setText(String.valueOf(totalAmountRequired));
                }

                resultSet.close();
                getPriceStatement.close();
                connection.close();
            } catch (SQLException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Invalid quantity.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_StockListMouseClicked

    private void BuyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuyButtonActionPerformed
        String selectedStockName = StockList.getSelectedItem();

    if (selectedStockName == null || selectedStockName.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please select a stock.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    try {
        Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/smms", "root", "FireRage@007");

        // Retrieve the price and Stock_ID of the selected stock
        PreparedStatement getPriceStatement = connection.prepareStatement("SELECT Price, Stock_ID FROM Company_Database WHERE Stock_Name = ?");
        getPriceStatement.setString(1, selectedStockName);
        ResultSet priceResultSet = getPriceStatement.executeQuery();

        if (priceResultSet.next()) {
            float price = priceResultSet.getFloat("Price");
            int stockID = priceResultSet.getInt("Stock_ID"); // Retrieve Stock_ID

            int quantity = Integer.parseInt(BuyQuantity.getText());
            float totalAmountRequired = price * quantity;

            // Retrieve user's available funds
            PreparedStatement getBalanceStatement = connection.prepareStatement("SELECT Funds_Available FROM profile_database WHERE User_ID = ?");
            getBalanceStatement.setInt(1, userID);
            ResultSet balanceResultSet = getBalanceStatement.executeQuery();

            if (balanceResultSet.next()) {
                float currentFunds = balanceResultSet.getFloat("Funds_Available");

                if (currentFunds >= totalAmountRequired) {
                    // Calculate new funds after purchase
                    float newFunds = currentFunds - totalAmountRequired;

                    // Update user's funds
                    PreparedStatement updateBalanceStatement = connection.prepareStatement("UPDATE profile_database SET Funds_Available = ? WHERE User_ID = ?");
                    updateBalanceStatement.setFloat(1, newFunds);
                    updateBalanceStatement.setInt(2, userID);
                    updateBalanceStatement.executeUpdate();

                    // Insert the order into the Orders table (auto-generated Order_ID)
                    PreparedStatement insertOrderStatement = connection.prepareStatement("INSERT INTO Orders (Status, Quantity, Stock_ID, Order_Type, Buy_Sell, User_ID) VALUES (1, ?, ?, 1, 1, ?)", Statement.RETURN_GENERATED_KEYS);
                    insertOrderStatement.setInt(1, quantity);
                    insertOrderStatement.setInt(2, stockID);
                    insertOrderStatement.setInt(3, userID);
                    insertOrderStatement.executeUpdate();

                    // Retrieve the auto-generated Order_ID
                    ResultSet generatedKeys = insertOrderStatement.getGeneratedKeys();
                    if (generatedKeys.next()) {
                        int orderID = generatedKeys.getInt(1);
                        JOptionPane.showMessageDialog(this, "Purchase successful! Order ID: " + orderID, "Success", JOptionPane.INFORMATION_MESSAGE);
                    }

                    generatedKeys.close();
                    insertOrderStatement.close();
                } else {
                    JOptionPane.showMessageDialog(this, "Insufficient funds.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }

            balanceResultSet.close();
            getBalanceStatement.close();
        }

        priceResultSet.close();
        getPriceStatement.close();
        connection.close();
    } catch (SQLException ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error purchasing stock: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "Invalid quantity.", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_BuyButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuyStocks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
       

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            // Check if command line arguments are provided
            if (args.length > 0) {
                // Convert the first argument to an integer (assuming it's the user ID)
                int userID = Integer.parseInt(args[0]);
                // Instantiate BuyStocks with the provided user ID
                BuyStocks buyStocks = new BuyStocks(userID);
                buyStocks.setVisible(true);
            } else {
                // If no user ID is provided, display an error message
                System.err.println("Error: No user ID provided.");
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AmountReq;
    private javax.swing.JButton BuyButton;
    private javax.swing.JTextField BuyQuantity;
    private java.awt.List StockList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
