/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.stockmarketsimulator;
import java.sql.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author parth
 */
public class SellStocks extends javax.swing.JFrame {
    private int userID;
    /**
     * Creates new form SellStocks
     */
    public SellStocks(int userID) {
        this.userID = userID;
        initComponents();
        displayUserStocks();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        UserStocksList = new java.awt.List();
        jLabel1 = new javax.swing.JLabel();
        QuantityToSell = new javax.swing.JTextField();
        SellButton = new javax.swing.JButton();

        label1.setText("label1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        UserStocksList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UserStocksListMouseClicked(evt);
            }
        });

        jLabel1.setText("Your Stocks:");

        QuantityToSell.setText("Quantity");

        SellButton.setText("Sell");
        SellButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SellButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(UserStocksList, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(QuantityToSell, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SellButton))))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UserStocksList, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(QuantityToSell, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SellButton)))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UserStocksListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserStocksListMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_UserStocksListMouseClicked

    private void SellButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SellButtonActionPerformed
        // TODO add your handling code here:
         String selectedStock = UserStocksList.getSelectedItem();
        if (selectedStock == null || selectedStock.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please select a stock to sell.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String[] parts = selectedStock.split(" - Quantity: ");
        String stockName = parts[0];
        int quantity = Integer.parseInt(QuantityToSell.getText().trim());

        if (quantity <= 0) {
            JOptionPane.showMessageDialog(this, "Please enter a valid quantity to sell.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/smms", "root", "FireRage@007");

            // Retrieve Stock_ID based on Stock_Name
            PreparedStatement stockStmt = connection.prepareStatement("SELECT Stock_ID FROM stocks WHERE Stock_Name = ?");
            stockStmt.setString(1, stockName);
            ResultSet stockRs = stockStmt.executeQuery();
            if (stockRs.next()) {
                int stockID = stockRs.getInt("Stock_ID");

                // Insert new order into Orders table
                PreparedStatement orderStmt = connection.prepareStatement(
                        "INSERT INTO Orders (Status, Quantity, Stock_ID, Order_Type, Buy_Sell, User_ID) " +
                        "VALUES (?, ?, ?, 1, 2, ?)");
                orderStmt.setInt(1, 1); // Status = 1 (Assuming status for new orders)
                orderStmt.setInt(2, quantity);
                orderStmt.setInt(3, stockID);
                orderStmt.setInt(4, userID);
                orderStmt.executeUpdate();

                JOptionPane.showMessageDialog(this, "Sell order placed successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
                displayUserStocks(); // Refresh the displayed user stocks after selling

                orderStmt.close();
            } else {
                JOptionPane.showMessageDialog(this, "Stock not found.", "Error", JOptionPane.ERROR_MESSAGE);
            }

            stockStmt.close();
            connection.close();

        } catch (SQLException ex) {
            ex.printStackTrace(); // Handle exception appropriately
            JOptionPane.showMessageDialog(this, "Error occurred while processing sell order.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_SellButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuyStocks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            // Check if command line arguments are provided
            if (args.length > 0) {
                // Convert the first argument to an integer (assuming it's the user ID)
                int userID = Integer.parseInt(args[0]);
                // Instantiate BuyStocks with the provided user ID
                SellStocks sellStocks = new SellStocks(userID);
                sellStocks.setVisible(true);
            } else {
                // If no user ID is provided, display an error message
                System.err.println("Error: No user ID provided.");
            }
        });
    }
    private void displayUserStocks() {
        Connection connection = null;
    PreparedStatement stmt = null;
    ResultSet rs = null;

    try {
        // Establish database connection
        connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/smms", "root", "FireRage@007");

        // Prepare SQL query to fetch user's stocks with stock names from joined tables
        String query = "SELECT s.Stock_Name, p.Qt FROM portfolio p " +
                       "INNER JOIN stocks s ON p.Stock_Id = s.Stock_Id " +
                       "WHERE p.User_Id = ?";
        stmt = connection.prepareStatement(query);
        stmt.setInt(1, userID); // Assuming User_Id corresponds to userID

        // Execute query
        rs = stmt.executeQuery();

        // Clear existing list items
        UserStocksList.removeAll();

        // Populate UserStocksList with user's stocks and their names
        while (rs.next()) {
            String stockName = rs.getString("Stock_Name");
            int quantity = rs.getInt("Qt");
            UserStocksList.add(stockName + " - Quantity: " + quantity);
        }

    } catch (SQLException ex) {
        ex.printStackTrace(); // Handle exception appropriately
    } finally {
        // Close resources
        try {
            if (rs != null) rs.close();
            if (stmt != null) stmt.close();
            if (connection != null) connection.close();
        } catch (SQLException ex) {
            ex.printStackTrace(); // Handle exception appropriately
        }
    }
    }

    // Other methods and components remain unchanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField QuantityToSell;
    private javax.swing.JButton SellButton;
    private java.awt.List UserStocksList;
    private javax.swing.JLabel jLabel1;
    private java.awt.Label label1;
    // End of variables declaration//GEN-END:variables
}
