/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.stockmarketsimulator;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
/**
 *
 * @author parth
 */
public class UserPage extends javax.swing.JFrame {
    private int userID;
     private static final String URL = "jdbc:mysql://localhost:3306/smms";
     private static final String USERNAME = "root";
     private static final String PASSWORD = "FireRage@007";
    /**
     * Creates new form UserPage
     */
    public UserPage(int intID) {
        this.userID = intID;
        initComponents();
        displayAvailableStocks();
    }
     private void displayAvailableStocks() {
        try {
        // Establish connection
        Connection connection = DriverManager.getConnection(URL, USERNAME, PASSWORD);
        // Prepare SQL statement
        String sql = "SELECT Stock_Name FROM stocks";
        PreparedStatement statement = connection.prepareStatement(sql);
        // Execute query
        ResultSet resultSet = statement.executeQuery();
        // Process result set
        while (resultSet.next()) {
            String stockName = resultSet.getString("Stock_Name");
            StockList.add(stockName);
        }
        // Close resources
        resultSet.close();
        statement.close();
        connection.close();
    } catch (SQLException ex) {
        ex.printStackTrace();
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        StockList = new java.awt.List();
        jLabel1 = new javax.swing.JLabel();
        BuyButton = new javax.swing.JButton();
        SellButton = new javax.swing.JButton();
        Profile = new javax.swing.JButton();
        AddFunds = new javax.swing.JTextField();
        AddFundsButton = new javax.swing.JButton();
        Withdraw = new javax.swing.JTextField();
        WithdrawButton = new javax.swing.JButton();
        PortfolioButton = new javax.swing.JButton();
        IPOButton = new javax.swing.JButton();
        Indices = new javax.swing.JButton();
        CustomIndex = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        StockList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StockListMouseClicked(evt);
            }
        });
        StockList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StockListActionPerformed(evt);
            }
        });

        jLabel1.setText("Stocks");

        BuyButton.setText("Buy");
        BuyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuyButtonActionPerformed(evt);
            }
        });

        SellButton.setText("Sell");
        SellButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SellButtonActionPerformed(evt);
            }
        });

        Profile.setText("Profile");
        Profile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProfileActionPerformed(evt);
            }
        });

        AddFunds.setText("AddFunds");

        AddFundsButton.setText("Add Funds");
        AddFundsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddFundsButtonActionPerformed(evt);
            }
        });

        Withdraw.setText("Withdraw");

        WithdrawButton.setText("Withdraw");
        WithdrawButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WithdrawButtonActionPerformed(evt);
            }
        });

        PortfolioButton.setText("Portfolio");
        PortfolioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PortfolioButtonActionPerformed(evt);
            }
        });

        IPOButton.setText("IPOs");
        IPOButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IPOButtonActionPerformed(evt);
            }
        });

        Indices.setText("Indices");
        Indices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IndicesActionPerformed(evt);
            }
        });

        CustomIndex.setText("Your Index");
        CustomIndex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomIndexActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(StockList, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BuyButton)
                                    .addComponent(SellButton)
                                    .addComponent(IPOButton)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AddFundsButton, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(AddFunds, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Withdraw, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(WithdrawButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(CustomIndex)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Indices)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PortfolioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Profile)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Profile)
                    .addComponent(PortfolioButton)
                    .addComponent(Indices)
                    .addComponent(CustomIndex))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(StockList, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BuyButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SellButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(IPOButton))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(AddFunds, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AddFundsButton)
                        .addGap(18, 18, 18)
                        .addComponent(Withdraw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(WithdrawButton)))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void StockListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StockListActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StockListActionPerformed

    private void StockListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StockListMouseClicked
        // TODO add your handling code here:
        String selectedStock = StockList.getSelectedItem();
    
    try {
        // Establish connection
        Connection connection = DriverManager.getConnection(URL, USERNAME, PASSWORD);
        // Prepare SQL statement to retrieve all information of the selected stock
        String sql = "SELECT * FROM stocks WHERE Stock_Name = ?";
        PreparedStatement statement = connection.prepareStatement(sql);
        statement.setString(1, selectedStock);
        // Execute query
        ResultSet resultSet = statement.executeQuery();
        // Check if the result set has data
        if (resultSet.next()) {
            // Retrieve and display the information of the selected stock
            String stockName = resultSet.getString("Stock_Name");
            double latestPrice = resultSet.getDouble("Latest_Price");
            double peRatio = resultSet.getDouble("PE");
            double earningsPerShare = resultSet.getDouble("EPS");
            double returnOnEquity = resultSet.getDouble("ROE");
            int stockID = resultSet.getInt("Stock_ID");
            // You can display this information wherever you want, for example:
            JOptionPane.showMessageDialog(this, "Stock Name: " + stockName + "\nLatest Price: $" + latestPrice + "\nPE Ratio: " + peRatio + "\nEarnings Per Share: " + earningsPerShare + "\nReturn On Equity: " + returnOnEquity + "\nStock ID: " + stockID);
        } else {
            // If no data found for the selected stock, display a message
            JOptionPane.showMessageDialog(this, "No information available for the selected stock.");
        }
        // Close resources
        resultSet.close();
        statement.close();
        connection.close();
    } catch (SQLException ex) {
        ex.printStackTrace();
    }
    }//GEN-LAST:event_StockListMouseClicked

    private void ProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProfileActionPerformed
        // TODO add your handling code here:
        try (Connection connection = DriverManager.getConnection(URL, USERNAME, PASSWORD)) {
        String sql = "SELECT * FROM profile_database WHERE User_Id = ?";
        PreparedStatement statement = connection.prepareStatement(sql);
        statement.setInt(1, userID);
        ResultSet resultSet = statement.executeQuery();

        if (resultSet.next()) {
            double fundsAvailable = resultSet.getDouble("Funds_Available");
            double fundsInvested = resultSet.getDouble("Funds_Invested");
            int portfolioId = resultSet.getInt("Portfolio_Id");
            double currentValue = resultSet.getDouble("Current_Value");

            // Display profile information in a dialog
            String profileInfo = "User ID: " + userID + "\n"
                    + "Funds Available: $" + fundsAvailable + "\n"
                    + "Funds Invested: $" + fundsInvested + "\n"
                    + "Portfolio ID: " + portfolioId + "\n"
                    + "Current Value: $" + currentValue;

            JOptionPane.showMessageDialog(this, profileInfo, "User Profile", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "User profile not found.", "Error", JOptionPane.ERROR_MESSAGE);
        }

        resultSet.close();
        statement.close();
    } catch (SQLException ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error retrieving user profile: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_ProfileActionPerformed

    private void AddFundsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddFundsButtonActionPerformed
        // TODO add your handling code here:
        String fundsToAddStr = AddFunds.getText().trim();
    
    // Validate and parse the input amount
    try {
        double fundsToAdd = Double.parseDouble(fundsToAddStr);
        
        if (fundsToAdd <= 0) {
            JOptionPane.showMessageDialog(this, "Please enter a valid amount to add.", "Invalid Amount", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Establish connection
        try (Connection connection = DriverManager.getConnection(URL, USERNAME, PASSWORD)) {
            // Retrieve current funds available
            String getCurrentFundsSql = "SELECT Funds_Available FROM profile_database WHERE User_Id = ?";
            PreparedStatement getCurrentFundsStatement = connection.prepareStatement(getCurrentFundsSql);
            getCurrentFundsStatement.setInt(1, userID);
            ResultSet currentFundsResultSet = getCurrentFundsStatement.executeQuery();
            
            if (currentFundsResultSet.next()) {
                double currentFunds = currentFundsResultSet.getDouble("Funds_Available");
                double newFunds = currentFunds + fundsToAdd;
                
                // Update funds available
                String updateFundsSql = "UPDATE profile_database SET Funds_Available = ? WHERE User_Id = ?";
                PreparedStatement updateFundsStatement = connection.prepareStatement(updateFundsSql);
                updateFundsStatement.setDouble(1, newFunds);
                updateFundsStatement.setInt(2, userID);
                
                int rowsUpdated = updateFundsStatement.executeUpdate();
                if (rowsUpdated > 0) {
                    JOptionPane.showMessageDialog(this, "Funds added successfully.", "Funds Added", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, "Failed to add funds.", "Error", JOptionPane.ERROR_MESSAGE);
                }
                
                updateFundsStatement.close();
            }
            
            currentFundsResultSet.close();
            getCurrentFundsStatement.close();
        }
        
    } catch (NumberFormatException | SQLException ex) {
        JOptionPane.showMessageDialog(this, "Error adding funds: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_AddFundsButtonActionPerformed

    private void WithdrawButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WithdrawButtonActionPerformed
        // TODO add your handling code here:
        // Get the amount to withdraw from the Withdraw text field
    String withdrawAmountStr = Withdraw.getText().trim();
    
    // Validate and parse the input amount
    try {
        double withdrawAmount = Double.parseDouble(withdrawAmountStr);
        
        if (withdrawAmount <= 0) {
            JOptionPane.showMessageDialog(this, "Please enter a valid amount to withdraw.", "Invalid Amount", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Establish connection
        try (Connection connection = DriverManager.getConnection(URL, USERNAME, PASSWORD)) {
            // Retrieve current funds available
            String getCurrentFundsSql = "SELECT Funds_Available FROM profile_database WHERE User_Id = ?";
            PreparedStatement getCurrentFundsStatement = connection.prepareStatement(getCurrentFundsSql);
            getCurrentFundsStatement.setInt(1, userID);
            ResultSet currentFundsResultSet = getCurrentFundsStatement.executeQuery();
            
            if (currentFundsResultSet.next()) {
                double currentFunds = currentFundsResultSet.getDouble("Funds_Available");
                
                // Check if sufficient funds are available for withdrawal
                if (currentFunds >= withdrawAmount) {
                    double newFunds = currentFunds - withdrawAmount;
                    
                    // Update funds available
                    String updateFundsSql = "UPDATE profile_database SET Funds_Available = ? WHERE User_Id = ?";
                    PreparedStatement updateFundsStatement = connection.prepareStatement(updateFundsSql);
                    updateFundsStatement.setDouble(1, newFunds);
                    updateFundsStatement.setInt(2, userID);
                    
                    int rowsUpdated = updateFundsStatement.executeUpdate();
                    if (rowsUpdated > 0) {
                        JOptionPane.showMessageDialog(this, "Funds withdrawn successfully.", "Funds Withdrawn", JOptionPane.INFORMATION_MESSAGE);
                    } else {
                        JOptionPane.showMessageDialog(this, "Failed to withdraw funds.", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                    
                    updateFundsStatement.close();
                } else {
                    JOptionPane.showMessageDialog(this, "Insufficient funds available for withdrawal.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
            
            currentFundsResultSet.close();
            getCurrentFundsStatement.close();
        }
        
    } catch (NumberFormatException | SQLException ex) {
        JOptionPane.showMessageDialog(this, "Error withdrawing funds: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_WithdrawButtonActionPerformed

    private void PortfolioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PortfolioButtonActionPerformed
        // TODO add your handling code here:
        try (Connection connection = DriverManager.getConnection(URL, USERNAME, PASSWORD)) {
            String sql = "SELECT * FROM Portfolio WHERE User_ID = ?";
            PreparedStatement statement = connection.prepareStatement(sql);
            statement.setInt(1, userID);
            ResultSet resultSet = statement.executeQuery();

            StringBuilder portfolioInfo = new StringBuilder();
            portfolioInfo.append("Portfolio Information for User ID: ").append(userID).append("\n\n");

            while (resultSet.next()) {
                int quantity = resultSet.getInt("Qt");
                double buyValue = resultSet.getDouble("Buy_Value");
                double latestPrice = resultSet.getDouble("Latest_Price");
                double eps = resultSet.getDouble("EPS");
                double pe = resultSet.getDouble("PE");
                double roe = resultSet.getDouble("ROE");
                int stockID = resultSet.getInt("Stock_ID");

                portfolioInfo.append("Stock ID: ").append(stockID).append("\n")
                            .append("Quantity: ").append(quantity).append("\n")
                            .append("Buy Value: $").append(buyValue).append("\n")
                            .append("Latest Price: $").append(latestPrice).append("\n")
                            .append("EPS: ").append(eps).append("\n")
                            .append("PE: ").append(pe).append("\n")
                            .append("ROE: ").append(roe).append("\n\n");
            }

            resultSet.close();
            statement.close();

            JOptionPane.showMessageDialog(this, portfolioInfo.toString(), "Portfolio Information", JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error retrieving portfolio information: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_PortfolioButtonActionPerformed

    private void BuyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuyButtonActionPerformed
        // TODO add your handling code here:
        BuyStocks buyStocksFrame = new BuyStocks(userID);
        buyStocksFrame.setVisible(true);
    }//GEN-LAST:event_BuyButtonActionPerformed

    private void SellButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SellButtonActionPerformed
        // TODO add your handling code here:
        SellStocks SellStocksFrame = new SellStocks(userID);
        SellStocksFrame.setVisible(true);
    }//GEN-LAST:event_SellButtonActionPerformed

    private void IPOButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IPOButtonActionPerformed
        // TODO add your handling code here:
        IPO ipoWindow = new IPO(userID);
        ipoWindow.setVisible(true);
    }//GEN-LAST:event_IPOButtonActionPerformed

    private void IndicesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IndicesActionPerformed
        // TODO add your handling code here:
        displayIndicesDialog();
    }//GEN-LAST:event_IndicesActionPerformed

    private void CustomIndexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomIndexActionPerformed
        // TODO add your handling code here:
        displayCustomIndexInfo();
    }//GEN-LAST:event_CustomIndexActionPerformed
    
    private void displayCustomIndexInfo() {
    try (Connection connection = DriverManager.getConnection(URL, USERNAME, PASSWORD)) {
        // Prepare SQL statement to retrieve custom index information for the current user
        String sql = "SELECT * FROM Customer_Index WHERE User_ID = ?";
        PreparedStatement statement = connection.prepareStatement(sql);
        statement.setInt(1, userID); // Set the User_ID parameter
        ResultSet resultSet = statement.executeQuery();

        StringBuilder customIndexInfo = new StringBuilder();
        customIndexInfo.append("Custom Index Information for User ID ").append(userID).append(":\n\n");

        // Append each custom index information to the StringBuilder
        while (resultSet.next()) {
            float priceBought = resultSet.getFloat("Price_Bought");
            float currentPrice = resultSet.getFloat("Current_Price");
            String indexID = resultSet.getString("Index_ID");

            customIndexInfo.append("Index ID: ").append(indexID)
                           .append("\nPrice Bought: $").append(priceBought)
                           .append("\nCurrent Price: $").append(currentPrice)
                           .append("\n\n");
        }

        // Show custom index information in a JOptionPane dialog
        JOptionPane.showMessageDialog(this, customIndexInfo.toString(), "Custom Index Information", JOptionPane.INFORMATION_MESSAGE);

        resultSet.close();
        statement.close();
    } catch (SQLException ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error fetching custom index information: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
}
    private void displayIndicesDialog() {
    try (Connection connection = DriverManager.getConnection(URL, USERNAME, PASSWORD)) {
        String sql = "SELECT Index_ID, Index_Name, Price FROM Indices";
        PreparedStatement statement = connection.prepareStatement(sql);
        ResultSet resultSet = statement.executeQuery();

        StringBuilder indicesInfo = new StringBuilder();
        indicesInfo.append("Available Indices:\n\n");

        // Append each index information to the StringBuilder
        while (resultSet.next()) {
            String indexID = resultSet.getString("Index_ID");
            String indexName = resultSet.getString("Index_Name");
            double price = resultSet.getDouble("Price");

            indicesInfo.append("Index ID: ").append(indexID)
                       .append(", Index Name: ").append(indexName)
                       .append(", Price: ").append(price).append("\n");
        }

        // Show indices information in a JOptionPane dialog
        JOptionPane.showMessageDialog(this, indicesInfo.toString(), "Available Indices", JOptionPane.INFORMATION_MESSAGE);

        resultSet.close();
        statement.close();
    } catch (SQLException ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error fetching indices: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ClassNotFoundException ex) {
        java.util.logging.Logger.getLogger(UserPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
        java.util.logging.Logger.getLogger(UserPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
        java.util.logging.Logger.getLogger(UserPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
        java.util.logging.Logger.getLogger(UserPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            // Check if command line arguments are provided
          
            if (args.length > 0) {
                // Convert the first argument to an integer (assuming it's the user ID)
                int userID = Integer.parseInt(args[0]);
                // Instantiate UserPage with the provided user ID
                UserPage userPage = new UserPage(userID);
                userPage.setVisible(true);
            } else {
                // If no user ID is provided, display an error message
                System.err.println("Error: No user ID provided.");
            }
        }
    });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AddFunds;
    private javax.swing.JButton AddFundsButton;
    private javax.swing.JButton BuyButton;
    private javax.swing.JButton CustomIndex;
    private javax.swing.JButton IPOButton;
    private javax.swing.JButton Indices;
    private javax.swing.JButton PortfolioButton;
    private javax.swing.JButton Profile;
    private javax.swing.JButton SellButton;
    private java.awt.List StockList;
    private javax.swing.JTextField Withdraw;
    private javax.swing.JButton WithdrawButton;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
